/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author jomro
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/imagenes/proyecto.png"));
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/imagenes/empleado.png"));
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/imagenes/riot.png"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(iconEmpleados.getWidth(), iconEmpleados.getHeight(), Image.SCALE_DEFAULT));
        Icon fondo2 = new ImageIcon(imagen2.getImage().getScaledInstance(iconProyectos.getWidth(), iconProyectos.getHeight(), Image.SCALE_DEFAULT));
        Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(iconRiot.getWidth(), iconRiot.getHeight(), Image.SCALE_DEFAULT));
        iconEmpleados.setIcon(fondo1);
        iconProyectos.setIcon(fondo2);
        iconRiot.setIcon(fondo3);
        this.repaint();
    }
    
    /**
     *
     * @return
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("/imagenes/riot.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jButtonProyectos = new javax.swing.JButton();
        jButtonEmpleados = new javax.swing.JButton();
        iconProyectos = new javax.swing.JLabel();
        iconEmpleados = new javax.swing.JLabel();
        iconRiot = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jButtonProyectos.setText("Proyectos");
        getContentPane().add(jButtonProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 100, -1));

        jButtonEmpleados.setText("Empleados");
        getContentPane().add(jButtonEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, -1));
        getContentPane().add(iconProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, 110));
        getContentPane().add(iconEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 120, 110));
        getContentPane().add(iconRiot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 190, 140));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconEmpleados;
    private javax.swing.JLabel iconProyectos;
    private javax.swing.JLabel iconRiot;
    public javax.swing.JButton jButtonEmpleados;
    public javax.swing.JButton jButtonProyectos;
    public javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables

    public void EXIT_ON_CLOSE() {
        System.exit(0);
    }

    
}
