/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author jomro
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        /*ImageIcon imagen1 = new ImageIcon(getClass().getResource("/src/imagenes/empleado.png"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(jLabelEmpleado.getWidth(), jLabelEmpleado.getHeight(), Image.SCALE_DEFAULT));
        jLabelEmpleado.setIcon(fondo1);
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/src/imagenes/proyecto.png"));
        Icon fondo2 = new ImageIcon(imagen2.getImage().getScaledInstance(jLabelProyecto.getWidth(), jLabelProyecto.getHeight(), Image.SCALE_DEFAULT));
        jLabelProyecto.setIcon(fondo2);
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/src/imagenes/riot.png"));
        Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(jLabelRiot.getWidth(), jLabelRiot.getHeight(), Image.SCALE_DEFAULT));
        jLabelRiot.setIcon(fondo3);
        this.repaint();*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jButtonEmpleado = new javax.swing.JButton();
        jButtonProyecto = new javax.swing.JButton();
        jLabelEmpleado = new javax.swing.JLabel();
        jLabelProyecto = new javax.swing.JLabel();
        jLabelRiot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        jButtonEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonEmpleado.setText("Empleados");
        getContentPane().add(jButtonEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        jButtonProyecto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonProyecto.setText("Proyectos");
        jButtonProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));
        getContentPane().add(jLabelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 180, 130));
        getContentPane().add(jLabelProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 180, 130));
        getContentPane().add(jLabelRiot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 220, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProyectoActionPerformed

    public void EXIT_ON_CLOSE() {
        System.exit(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonEmpleado;
    public javax.swing.JButton jButtonProyecto;
    public javax.swing.JButton jButtonSalir;
    public javax.swing.JLabel jLabelEmpleado;
    public javax.swing.JLabel jLabelProyecto;
    public javax.swing.JLabel jLabelRiot;
    // End of variables declaration//GEN-END:variables
}
